# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'spanjaan.sm::lang.models.project.label'

# Model Form Field configuration
form: $/spanjaan/sm/models/project/fields.yaml

# Model Class name
modelClass: SpAnjaan\Sm\Models\Project

# Default redirect location
defaultRedirect: spanjaan/sm/projects

# Create page
create:
    title: backend::lang.form.create_title
    redirect: spanjaan/sm/projects/update/:id
    redirectClose: spanjaan/sm/projects

# Update page
update:
    title: backend::lang.form.update_title
    redirect: spanjaan/sm/projects
    redirectClose: spanjaan/sm/projects

# Preview page
preview:
    title: backend::lang.form.preview_title
